"use client";
import { useEffect, useState } from "react";
import { Copy, KeyRound, LockKeyhole, LogOut, ShieldCheck, UserRound } from "lucide-react";
import { onAuthStateChanged, signOut, type User } from "firebase/auth";
import { auth } from "../lib/firebase";
import StandaloneShell from "./standalone-shell";
export default function ProfilePage(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]);
 const logout=async()=>{await signOut(auth);window.location.href="/"};
 const copyApi=async()=>{await navigator.clipboard.writeText("https://kitsetups.xyz/api/signals");setCopied(true);setTimeout(()=>setCopied(false),1600)};
 if(loading)return <StandaloneShell title="PROFILE"><div className="rounded-2xl border border-zinc-800 bg-zinc-950 px-6 py-16 text-center"><div className="mx-auto h-5 w-5 animate-spin rounded-full border-2 border-zinc-800 border-t-cyan-400"/><p className="mt-4 text-xs text-zinc-500">Restoring your account session…</p></div></StandaloneShell>;
 return <StandaloneShell title="PROFILE"><div className="space-y-4">
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-center gap-4"><div className="h-16 w-16 overflow-hidden rounded-full border border-zinc-800 bg-black">{user?.photoURL?<img src={user.photoURL} alt="Profile" className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center"><UserRound className="h-6 w-6 text-zinc-700"/></div>}</div><div className="min-w-0"><p className="text-base font-medium text-white">{user?.displayName||"KitSetups user"}</p><p className="mt-1 truncate text-xs text-zinc-500">{user?.email||"Signed-in account"}</p><p className="mt-2 font-mono text-[8px] tracking-[.18em] text-emerald-400">AUTHENTICATED</p></div></div></section>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium"><KeyRound className="h-4 w-4 text-cyan-400"/>Developer API</p><p className="mt-2 text-xs leading-5 text-zinc-500">Display KitSetups signals inside your own dashboard, bot or trading application. API keys and permissions will be managed here.</p></div><span className="rounded-full border border-cyan-500/20 bg-cyan-500/5 px-2 py-1 font-mono text-[8px] text-cyan-400">COMING SOON</span></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-zinc-900 bg-black/50 p-3"><code className="min-w-0 flex-1 truncate text-[10px] text-zinc-500">https://kitsetups.xyz/api/signals</code><button onClick={copyApi} className="shrink-0 rounded-lg border border-zinc-800 p-2 text-zinc-500 hover:text-cyan-400" aria-label="Copy API endpoint"><Copy className="h-3.5 w-3.5"/></button></div><p className="mt-2 text-[9px] text-zinc-700">{copied?"Endpoint copied":"Integration endpoint reserved for the KitSetups Signals API."}</p></section>
  <section className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><LockKeyhole className="h-4 w-4 text-zinc-600"/><p className="mt-3 font-mono text-[9px] text-zinc-600">ACCOUNT DATA</p><p className="mt-1 text-xs text-zinc-500">Name and profile image are read directly from the authenticated Firebase account.</p></div><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><ShieldCheck className="h-4 w-4 text-zinc-600"/><p className="mt-3 font-mono text-[9px] text-zinc-600">DATA MODE</p><p className="mt-1 text-xs text-zinc-500">Standalone UI · trading backend disconnected</p></div></section>
  <button onClick={logout} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-xs font-medium text-red-400 transition hover:border-red-500/40 hover:bg-red-500/10"><LogOut className="h-4 w-4"/>Log out</button>
 </div></StandaloneShell>;
}
