"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Copy, KeyRound, LockKeyhole, LogOut, ShieldCheck, UserRound, Wallet, Loader2, ExternalLink } from "lucide-react";
import { onAuthStateChanged, signOut, type User } from "firebase/auth";
import { auth } from "../lib/firebase";
import StandaloneShell from "./standalone-shell";

const FREE_MS=3*24*60*60*1000;
const PREMIUM_MS=30*24*60*60*1000;
const PAYMENT_ADDRESS=process.env.NEXT_PUBLIC_BNB_USDT_PAYMENT_ADDRESS||"";
const USDT_BSC="0x55d398326f99059ff775485246999027b3197955";

function countdown(target:number){
 const ms=Math.max(0,target-Date.now());
 const total=Math.floor(ms/1000),days=Math.floor(total/86400),hours=Math.floor((total%86400)/3600),minutes=Math.floor((total%3600)/60),seconds=total%60;
 return {ms,days,hours,minutes,seconds};
}
function formatAddress(v:string){return v?v.slice(0,7)+"…"+v.slice(-5):"Wallet address will appear here"}

export default function ProfilePage(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[now,setNow]=useState(Date.now()),[txHash,setTxHash]=useState(""),[verifyState,setVerifyState]=useState(""),[premiumUntil,setPremiumUntil]=useState<number|null>(null);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);if(u){const profile={uid:u.uid,name:u.displayName||"",image:u.photoURL||"",email:u.email||"",createdAt:u.metadata.creationTime||new Date().toISOString()};localStorage.setItem("kitsetups_user_profile",JSON.stringify(profile));const saved=Number(localStorage.getItem("kitsetups_premium_until")||0);if(saved>0)setPremiumUntil(saved)}else localStorage.removeItem("kitsetups_user_profile");setLoading(false)}),[]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
 const createdAt=useMemo(()=>user?.metadata.creationTime?new Date(user.metadata.creationTime).getTime():now,[user,now]);
 const premiumActive=!!premiumUntil&&premiumUntil>now;
 const freeUntil=createdAt+FREE_MS;
 const freeActive=!premiumActive&&freeUntil>now;
 const target=premiumActive?premiumUntil!:freeUntil;
 const left=countdown(target);
 const plan=premiumActive?"PREMIUM":freeActive?"FREE TRIAL":"EXPIRED";
 const copyWallet=async()=>{if(!PAYMENT_ADDRESS)return;await navigator.clipboard.writeText(PAYMENT_ADDRESS);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 const verifyPayment=async()=>{if(!txHash.trim()){setVerifyState("Enter your transaction hash first.");return}setVerifyState("Verifying transaction…");try{const r=await fetch("/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({txHash:txHash.trim()})});const d=await r.json();if(!r.ok||!d.verified){setVerifyState(d.error||"Payment could not be verified.");return}const expiry=Date.now()+PREMIUM_MS;localStorage.setItem("kitsetups_premium_until",String(expiry));setPremiumUntil(expiry);setVerifyState("Payment verified. Premium is now active for 30 days.")}catch{setVerifyState("Verification service is temporarily unavailable. Please try again.")}};
 const logout=async()=>{await signOut(auth);window.location.href="/"};
 if(loading)return <StandaloneShell title="PROFILE"><div className="rounded-2xl border border-zinc-800 bg-zinc-950 px-6 py-16 text-center"><div className="mx-auto h-5 w-5 animate-spin rounded-full border-2 border-zinc-800 border-t-cyan-400"/><p className="mt-4 text-xs text-zinc-500">Restoring your account session…</p></div></StandaloneShell>;
 return <StandaloneShell title="PROFILE"><div className="space-y-4">
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-center gap-4"><div className="h-16 w-16 overflow-hidden rounded-full border border-zinc-800 bg-black">{user?.photoURL?<img src={user.photoURL} alt="Profile" className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center"><UserRound className="h-6 w-6 text-zinc-700"/></div>}</div><div className="min-w-0 flex-1"><p className="text-base font-medium text-white">{user?.displayName||"KitSetups user"}</p><p className="mt-1 truncate text-xs text-zinc-500">{user?.email||"Signed-in account"}</p><p className="mt-2 font-mono text-[8px] tracking-[.18em] text-emerald-400">AUTHENTICATED</p></div><span className={`rounded-full border px-2 py-1 font-mono text-[8px] ${premiumActive?"border-cyan-500/20 bg-cyan-500/5 text-cyan-400":freeActive?"border-emerald-500/20 bg-emerald-500/5 text-emerald-400":"border-red-500/20 bg-red-500/5 text-red-400"}`}>{plan}</span></div></section>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] tracking-[.2em] text-zinc-600">ACCOUNT DETAILS</p><h2 className="mt-2 text-sm font-medium">Account & access tracker</h2></div><ShieldCheck className="h-4 w-4 text-cyan-400"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><p className="font-mono text-[8px] text-zinc-600">ACCOUNT CREATED</p><p className="mt-2 text-sm text-zinc-300">{new Date(createdAt).toLocaleString()}</p></div><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><p className="font-mono text-[8px] text-zinc-600">CURRENT ACCESS</p><p className="mt-2 text-sm text-zinc-300">{premiumActive?"Premium signals":"Free trial signals"}</p></div></div><div className="mt-4 rounded-xl border border-zinc-900 bg-black/40 p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-mono text-[9px] text-zinc-500"><Clock3 className="h-3.5 w-3.5"/>ACCESS TIMER</span><Loader2 className="h-3.5 w-3.5 animate-spin text-cyan-400"/></div><div className="mt-3 flex items-end gap-2"><span className={`font-mono text-2xl font-semibold ${plan==="EXPIRED"?"text-red-400":"text-white"}`}>{left.days}d {left.hours}h</span><span className="pb-1 font-mono text-[9px] text-zinc-600">{left.minutes}m {left.seconds}s left</span></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-zinc-900"><div className={`h-full transition-all ${plan==="PREMIUM"?"bg-cyan-400":"bg-emerald-400"}`} style={{width:`${Math.max(0,Math.min(100,(left.ms/(plan==="PREMIUM"?PREMIUM_MS:FREE_MS))*100))}%`}}/></div><p className="mt-2 text-[9px] text-zinc-700">{plan==="PREMIUM"?"Premium access expires after 30 days.":plan==="FREE"?"Your free access lasts 3 days from signup.":"Your access has expired. Subscribe to restore full setup visibility."}</p></div></section>
  <section className="rounded-2xl border border-cyan-500/15 bg-zinc-950 p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium"><Wallet className="h-4 w-4 text-cyan-400"/>Premium access</p><p className="mt-2 text-xs leading-5 text-zinc-500">30 days of full KitSetups setup visibility for <span className="text-zinc-300">$30 USDT</span> on BNB Smart Chain.</p></div><span className="rounded-full border border-cyan-500/20 bg-cyan-500/5 px-2 py-1 font-mono text-[8px] text-cyan-400">30 DAYS</span></div><div className="mt-4 rounded-xl border border-zinc-900 bg-black/50 p-4"><p className="font-mono text-[8px] text-zinc-600">PAY WITH USDT · BNB SMART CHAIN</p><div className="mt-3 flex items-center gap-2"><code className="min-w-0 flex-1 break-all text-[10px] text-zinc-400">{formatAddress(PAYMENT_ADDRESS)}</code><button onClick={copyWallet} disabled={!PAYMENT_ADDRESS} className="shrink-0 rounded-lg border border-zinc-800 p-2 text-zinc-500 hover:text-cyan-400 disabled:opacity-30" aria-label="Copy payment wallet"><Copy className="h-3.5 w-3.5"/></button></div><p className="mt-2 text-[9px] text-zinc-700">{copied?"Wallet copied":"Send exactly 30 USDT, then submit the transaction hash below."}</p></div><div className="mt-4"><label className="font-mono text-[8px] text-zinc-600">TRANSACTION HASH</label><div className="mt-2 flex gap-2"><input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="0x…" className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-black/50 px-3 py-3 text-xs text-white outline-none placeholder:text-zinc-700 focus:border-cyan-500/40"/><button onClick={verifyPayment} className="shrink-0 rounded-xl bg-cyan-400 px-4 py-3 text-xs font-semibold text-black transition hover:bg-cyan-300">Verify</button></div><p className={`mt-2 text-[9px] ${verifyState.includes("verified")?"text-emerald-400":"text-zinc-600"}`}>{verifyState}</p></div><a href={txHash?`https://bscscan.com/tx/${txHash}`:"https://bscscan.com"} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[9px] font-mono text-zinc-600 hover:text-cyan-400">VIEW ON BSCSCAN <ExternalLink className="h-3 w-3"/></a><p className="mt-3 text-[9px] leading-4 text-zinc-700">Verification checks the BNB Smart Chain transaction, recipient, USDT contract and required amount before premium access is activated.</p></section>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium"><KeyRound className="h-4 w-4 text-cyan-400"/>Developer API</p><p className="mt-2 text-xs leading-5 text-zinc-500">Display KitSetups signals inside your own dashboard, bot or trading application. API keys and permissions will be managed here.</p></div><span className="rounded-full border border-cyan-500/20 bg-cyan-500/5 px-2 py-1 font-mono text-[8px] text-cyan-400">COMING SOON</span></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-zinc-900 bg-black/50 p-3"><code className="min-w-0 flex-1 truncate text-[10px] text-zinc-500">https://kitsetups.xyz/api/signals</code></div></section>
  <section className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><LockKeyhole className="h-4 w-4 text-zinc-600"/><p className="mt-3 font-mono text-[9px] text-zinc-600">ACCOUNT DATA</p><p className="mt-1 text-xs text-zinc-500">Name, image, UID and creation time are captured from Firebase authentication.</p></div><div className="rounded-xl border border-zinc-900 bg-black/40 p-4"><ShieldCheck className="h-4 w-4 text-zinc-600"/><p className="mt-3 font-mono text-[9px] text-zinc-600">ACCESS RULES</p><p className="mt-1 text-xs text-zinc-500">Free: 3 days · Premium: 30 days · Expired: setups locked.</p></div></section>
  <button onClick={logout} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-xs font-medium text-red-400 transition hover:border-red-500/40 hover:bg-red-500/10"><LogOut className="h-4 w-4"/>Log out</button>
 </div></StandaloneShell>;
}
