"use client";
import { useEffect, useMemo, useState } from "react";
import { Clock3, Copy, KeyRound, LogOut, ShieldCheck, UserRound, Wallet, Loader2, ExternalLink, Sparkles } from "lucide-react";
import { onAuthStateChanged, signOut, type User } from "firebase/auth";
import { auth } from "../lib/firebase";
import StandaloneShell from "./standalone-shell";
import { kitsetupsApi } from "../lib/api";

const API_BASE=kitsetupsApi("");
const PREMIUM_MS=30*24*60*60*1000;
const PAYMENT_ADDRESS=process.env.NEXT_PUBLIC_BNB_USDT_PAYMENT_ADDRESS||"";

type Account={displayName?:string;email?:string;photoURL?:string|null;createdAt?:string;trialEndsAt?:string;plan?:string;planName?:string;subscriptionEndsAt?:string;accessStatus?:string;accessLocked?:boolean;accessExpiresAt?:string|null};
function countdown(target:number){const ms=Math.max(0,target-Date.now());const total=Math.floor(ms/1000);return{ms,days:Math.floor(total/86400),hours:Math.floor(total%86400/3600),minutes:Math.floor(total%3600/60),seconds:total%60}}
function formatAddress(v:string){return v?v.slice(0,7)+"…"+v.slice(-5):"Payment wallet will appear here"}

export default function ProfilePage(){
  const[user,setUser]=useState<User|null>(null),[account,setAccount]=useState<Account|null>(null),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[now,setNow]=useState(Date.now()),[txHash,setTxHash]=useState(""),[verifyState,setVerifyState]=useState("");
  useEffect(()=>{const unsubscribe=onAuthStateChanged(auth,async u=>{setUser(u);if(!u){setAccount(null);setLoading(false);return}try{const token=await u.getIdToken();const r=await fetch(`${API_BASE}/api/account`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok){await signOut(auth);setAccount(null);return}const d=await r.json();setAccount(d.data||null)}catch{setAccount(null)}finally{setLoading(false)}});return()=>unsubscribe()},[]);
  useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
  const createdAt=useMemo(()=>account?.createdAt?new Date(account.createdAt).getTime():now,[account,now]);
  const trialUntil=account?.trialEndsAt?new Date(account.trialEndsAt).getTime():createdAt;
  const premiumUntil=account?.subscriptionEndsAt?new Date(account.subscriptionEndsAt).getTime():0;
  const premiumActive=(account?.plan==="premium"||account?.planName==="Premium")&&premiumUntil>now;
  const freeActive=!premiumActive&&trialUntil>now;
  const target=premiumActive?premiumUntil:trialUntil;
  const left=countdown(target);
  const plan=premiumActive?"PREMIUM":freeActive?"FREE TRIAL":"EXPIRED";
  const copyWallet=async()=>{if(!PAYMENT_ADDRESS)return;await navigator.clipboard.writeText(PAYMENT_ADDRESS);setCopied(true);setTimeout(()=>setCopied(false),1600)};
  const refreshAccount=async()=>{const u=auth.currentUser;if(!u)return;const token=await u.getIdToken(true);const r=await fetch(`${API_BASE}/api/account`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(r.ok){const d=await r.json();setAccount(d.data||null)}};
  const verifyPayment=async()=>{if(!txHash.trim()){setVerifyState("Enter your transaction hash first.");return}setVerifyState("Verifying transaction on BNB Smart Chain…");try{const u=auth.currentUser;if(!u)throw new Error("Please sign in again.");const token=await u.getIdToken(true);const r=await fetch(`${API_BASE}/api/payment/verify`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({txHash:txHash.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok){setVerifyState(d.error||"Payment could not be verified.");return}await refreshAccount();setVerifyState(`Payment verified. Premium is active for ${d.data?.days||30} days.`)}catch(e:any){setVerifyState(e?.message||"Verification service is temporarily unavailable. Please try again.")}};
  const logout=async()=>{await signOut(auth);window.location.href="/auth"};
  if(loading)return <StandaloneShell title="PROFILE"><div className="nart-card rounded-2xl border border-zinc-800/80 bg-zinc-950/80 px-6 py-16 text-center"><div className="mx-auto h-5 w-5 animate-spin rounded-full border-2 border-zinc-800 border-t-cyan-400"/><p className="mt-4 text-xs text-zinc-500">Restoring your account session…</p></div></StandaloneShell>;
  return <StandaloneShell title="PROFILE"><div className="space-y-4">
    <section className="nart-card overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950/85 p-4 sm:p-5"><div className="flex items-center gap-3 sm:gap-4"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-full border border-cyan-400/20 bg-black shadow-[0_0_24px_rgba(34,211,238,.08)] sm:h-16 sm:w-16">{user?.photoURL?<img src={user.photoURL} alt="Profile" className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center"><UserRound className="h-6 w-6 text-zinc-700"/></div>}</div><div className="min-w-0 flex-1"><p className="truncate text-base font-medium text-white">{user?.displayName||account?.displayName||"KitSetups user"}</p><p className="mt-1 truncate text-xs text-zinc-500">{user?.email||account?.email||"Signed-in account"}</p><p className="mt-2 font-mono text-[8px] tracking-[.18em] text-emerald-400">SERVER VERIFIED</p></div><span className={`shrink-0 rounded-full border px-2 py-1 font-mono text-[8px] ${premiumActive?"border-amber-400/30 bg-amber-400/10 text-amber-300":freeActive?"border-emerald-500/20 bg-emerald-500/5 text-emerald-400":"border-red-500/20 bg-red-500/5 text-red-400"}`}>{plan}</span></div></section>
    <section className="nart-card rounded-2xl border border-cyan-500/15 bg-gradient-to-br from-zinc-950 via-zinc-950 to-cyan-950/20 p-4 shadow-[0_12px_45px_rgba(34,211,238,.04)]"><div className="flex items-center justify-between"><div><p className="font-mono text-[8px] tracking-[.2em] text-cyan-400/70">ACCOUNT</p><h2 className="mt-1 text-sm font-medium text-white">Account & access</h2></div><div className="flex h-8 w-8 items-center justify-center rounded-lg border border-cyan-400/15 bg-cyan-400/5"><ShieldCheck className="h-4 w-4 text-cyan-300"/></div></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/5 bg-black/40 px-3 py-2.5"><p className="font-mono text-[7px] tracking-wider text-zinc-600">CREATED</p><p className="mt-1.5 text-[11px] text-zinc-300">{new Date(createdAt).toLocaleDateString()}</p></div><div className="rounded-xl border border-white/5 bg-black/40 px-3 py-2.5"><p className="font-mono text-[7px] tracking-wider text-zinc-600">ACCESS</p><p className={`mt-1.5 text-[11px] ${premiumActive?"text-amber-300":"text-zinc-300"}`}>{premiumActive?"Premium":freeActive?"Free trial":"Locked"}</p></div></div><div className="mt-2.5 rounded-xl border border-white/5 bg-black/50 px-3 py-3"><div className="flex items-center justify-between"><span className="flex items-center gap-1.5 font-mono text-[7px] tracking-wider text-zinc-500"><Clock3 className="h-3 w-3 text-cyan-400"/>ACCESS TIMER</span><Loader2 className="h-3 w-3 animate-spin text-cyan-400"/></div><div className="mt-2 flex items-baseline justify-between"><span className={`font-mono text-xl font-semibold ${plan==="EXPIRED"?"text-red-400":premiumActive?"text-amber-300":"text-white"}`}>{left.days}d {left.hours}h</span><span className="font-mono text-[8px] text-zinc-600">{left.minutes}m {left.seconds}s</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-zinc-900"><div className={`h-full transition-all ${premiumActive?"bg-amber-300":"bg-emerald-400"}`} style={{width:`${Math.max(0,Math.min(100,left.ms/(premiumActive?PREMIUM_MS:Math.max(PREMIUM_MS,trialUntil-createdAt))*100))}%`}}/></div><p className="mt-1.5 text-[8px] text-zinc-700">{premiumActive?"Premium access expires after the server-issued subscription period.":freeActive?"Free access expires according to the server-issued trial period.":"Access expired. Subscribe to restore setup visibility."}</p></div></section>
    <section className="nart-card relative overflow-hidden rounded-2xl border border-amber-400/20 bg-gradient-to-br from-[#100e08] via-zinc-950 to-zinc-950 p-4 shadow-[0_18px_55px_rgba(251,191,36,.06)] sm:p-5"><div className="pointer-events-none absolute -right-12 -top-12 h-32 w-32 rounded-full bg-amber-300/10 blur-3xl"/><div className="relative"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-medium text-white"><span className="flex h-7 w-7 items-center justify-center rounded-lg border border-amber-300/20 bg-amber-300/10"><Wallet className="h-4 w-4 text-amber-300"/></span>Premium access</p><p className="mt-2 text-xs leading-5 text-zinc-500">30 days of full KitSetups setup visibility for <span className="font-medium text-amber-200">$30 USDT</span> on BNB Smart Chain.</p></div><span className="flex shrink-0 items-center gap-1 rounded-full border border-amber-300/30 bg-amber-300/10 px-2.5 py-1 font-mono text-[8px] font-semibold text-amber-300"><Sparkles className="h-3 w-3"/>30 DAYS</span></div><div className="mt-4 rounded-xl border border-amber-300/10 bg-black/50 p-3 sm:p-4"><p className="font-mono text-[8px] text-amber-200/50">PAY WITH USDT · BNB SMART CHAIN</p><div className="mt-3 flex items-center gap-2"><code className="min-w-0 flex-1 break-all text-[10px] text-zinc-400">{formatAddress(PAYMENT_ADDRESS)}</code><button onClick={copyWallet} disabled={!PAYMENT_ADDRESS} className="shrink-0 rounded-lg border border-amber-300/15 bg-amber-300/5 p-2 text-zinc-500 transition hover:border-amber-300/30 hover:text-amber-300 disabled:opacity-30"><Copy className="h-3.5 w-3.5"/></button></div><p className="mt-2 text-[9px] text-zinc-700">{copied?"Wallet copied":"Send exactly 30 USDT, then submit the transaction hash below."}</p></div><div className="mt-4"><label className="font-mono text-[8px] text-zinc-600">TRANSACTION HASH</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="0x…" className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-black/50 px-3 py-3 text-xs text-white outline-none placeholder:text-zinc-700 focus:border-amber-300/40"/><button onClick={verifyPayment} className="rounded-xl bg-amber-300 px-4 py-3 text-xs font-semibold text-black transition hover:bg-amber-200 sm:shrink-0">Verify</button></div><p className={`mt-2 text-[9px] ${verifyState.includes("verified")?"text-emerald-400":"text-zinc-600"}`}>{verifyState}</p></div><a href={txHash?`https://bscscan.com/tx/${txHash}`:"https://bscscan.com"} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[9px] font-mono text-zinc-600 hover:text-amber-300">VIEW ON BSCSCAN <ExternalLink className="h-3 w-3"/></a><p className="mt-3 text-[9px] leading-4 text-zinc-700">Verification is performed by the KitSetups backend and the resulting subscription is stored server-side.</p></div></section>
    <section className="nart-card rounded-2xl border border-zinc-800/80 bg-zinc-950/80 p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium"><KeyRound className="h-4 w-4 text-cyan-400"/>Developer API</p><p className="mt-2 text-xs leading-5 text-zinc-500">Display KitSetups signals inside your own dashboard, bot or trading application. API keys and permissions will be managed here.</p></div><span className="shrink-0 rounded-full border border-cyan-500/20 bg-cyan-500/5 px-2 py-1 font-mono text-[8px] text-cyan-400">COMING SOON</span></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-zinc-900 bg-black/50 p-3"><code className="min-w-0 flex-1 truncate text-[10px] text-zinc-500">https://kitsetups.xyz/api/signals</code></div></section>
    <button onClick={logout} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-xs font-medium text-red-400 transition hover:border-red-500/40 hover:bg-red-500/10"><LogOut className="h-4 w-4"/>Log out</button>
  </div></StandaloneShell>
}
