"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {ArrowUpRight,BarChart3,Clock3,Crosshair,RefreshCw,ShieldCheck,Target,TrendingDown,TrendingUp} from "lucide-react";
import StandaloneShell from "./standalone-shell";
import {auth} from "../lib/firebase";
import {kitsetupsAuthFetch} from "../lib/api";
type Signal=any;
const fmt=(v:unknown,d=2)=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d}):"—"};
const label=(v:unknown)=>String(v||"—").replaceAll("_"," ").toUpperCase();
const state=(s:Signal)=>String(s?.lifecycle?.status||s?.status||"WAIT").toUpperCase();
const active=new Set(["READY","ENTRY_HIT","ACTIVE","TP1_HIT","TP2_HIT","TP3_HIT"]);
function tfRows(s:Signal){const t=s?.analysis?.context?.timeframes||{};const st=s?.analysis?.structures||{};return ["1w","1d","4h","1h","30m"].map(tf=>({tf,trend:t[tf]?.trend||st[tf]?.direction||"neutral",structure:st[tf]?.breaks?.latest?.kind||"—",level:st[tf]?.breaks?.latest?.level}));}
export default function SetupsPageView(){
 const[signals,setSignals]=useState<Signal[]>([]),[scanner,setScanner]=useState<Signal>(null),[access,setAccess]=useState<Signal>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(silent=false)=>{const user=auth.currentUser;if(!user){setLoading(false);setError("Sign in to view live setups.");return}silent?setRefreshing(true):setLoading(true);setError("");try{const token=await user.getIdToken(),r=await kitsetupsAuthFetch("/api/signals",token),b=await r.json();if(!r.ok||!b?.ok)throw new Error(b?.error||"Unable to load setups");const d=b.data||{};setSignals(Array.isArray(d.signals)?d.signals:Array.isArray(d.scanResults)?d.scanResults:[]);setScanner(d.scanner||null);setAccess(d.access||null)}catch(e){setError(e instanceof Error?e.message:"Unable to load live setups.")}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{let mounted=true;const boot=async()=>{await auth.authStateReady();if(mounted)await load()};void boot();const id=window.setInterval(()=>{if(auth.currentUser)void load(true)},15000);return()=>{mounted=false;window.clearInterval(id)}},[load]);
 const ready=signals.filter(s=>active.has(state(s))&&s.valid!==false),visible=[...signals].sort((a,b)=>Number(b?.quality?.score||0)-Number(a?.quality?.score||0)),hasAccess=Boolean(access?.hasAccess);
 return <StandaloneShell title="SETUPS"><section className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] tracking-[.22em] text-cyan-500">TRADE RADAR</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-zinc-100">Evaluated opportunities</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-zinc-600">The engine reads context, structure, liquidity and momentum together before publishing a trade plan.</p></div><button onClick={()=>void load(true)} disabled={loading||refreshing} className="inline-flex h-10 items-center gap-2 rounded-xl border border-zinc-800 bg-zinc-950 px-3.5 font-mono text-[9px] tracking-[.12em] text-zinc-500 transition hover:border-cyan-400/20 hover:text-cyan-300 disabled:opacity-40"><RefreshCw className={refreshing?"h-3.5 w-3.5 animate-spin":"h-3.5 w-3.5"}/>REFRESH</button></section>
 {error&&<div className="mb-5 rounded-2xl border border-amber-500/15 bg-amber-500/[.035] p-4 text-xs text-amber-300">{error}</div>}
 <section className="mb-5 grid gap-3 sm:grid-cols-4"><Stat icon={<Crosshair/>} label="SCANNED" value={fmt(scanner?.scannedSymbols||signals.length,0)}/><Stat icon={<BarChart3/>} label="READY" value={fmt(scanner?.readySignals??ready.length,0)}/><Stat icon={<Clock3/>} label="WAITING" value={fmt(scanner?.waitSignals??signals.filter(s=>state(s)==="WAIT").length,0)}/><Stat icon={<ShieldCheck/>} label="ENGINE" value={label(scanner?.status||"LIVE")}/></section>
 {!hasAccess&&<div className="mb-5 rounded-2xl border border-cyan-400/10 bg-cyan-400/[.025] px-4 py-3 text-xs text-zinc-500"><span className="font-medium text-zinc-300">Live market intelligence is available.</span> Execution prices remain protected until access is active.</div>}
 {loading&&!signals.length?<div className="grid gap-3 lg:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="h-64 animate-pulse rounded-2xl border border-zinc-900 bg-zinc-950/70"/>)}</div>:visible.length?<div className="grid gap-4">{visible.map((s,i)=><TradeCard key={s?.signalId||s?.symbol||i} signal={s} hasAccess={hasAccess}/>)}</div>:<div className="rounded-2xl border border-zinc-800/80 bg-zinc-950/75 px-5 py-14 text-center"><Crosshair className="mx-auto h-6 w-6 text-zinc-700"/><h3 className="mt-4 text-sm font-medium text-zinc-300">No coherent setup right now</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-zinc-600">The scanner is connected to live market data. A setup appears when the combined evidence supports a trade thesis.</p></div>}
 <div className="mt-4 flex items-center gap-2 font-mono text-[8px] text-zinc-700">LIVE ENGINE {scanner?.updatedAt?`· UPDATED ${new Date(scanner.updatedAt).toLocaleString()}`:""}</div></StandaloneShell>;
}
function TradeCard({signal:s,hasAccess}:{signal:Signal;hasAccess:boolean}){const st=state(s),dir=String(s?.direction||"").toUpperCase(),score=Number(s?.quality?.score||0),rows=tfRows(s),th=s?.thesis||{},targets=Array.isArray(s?.targets)?s.targets:[],id=s?.signalId||s?.id;return <article className="overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950/80 shadow-[0_0_40px_rgba(0,0,0,.12)]"><div className="p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold tracking-tight text-zinc-100">{s?.symbol||"—"}</h2><Badge good={active.has(st)}>{label(st)}</Badge><Badge>{label(s?.setupType||"SETUP")}</Badge></div><div className="mt-2 flex items-center gap-3"><span className={`text-sm font-semibold ${dir==="LONG"?"text-emerald-300":dir==="SHORT"?"text-red-300":"text-zinc-400"}`}>{dir||"WATCH"}</span><span className="text-xs text-zinc-600">{label(s?.marketRegime||"UNKNOWN")} · {label(s?.timeframe||"30M")}</span></div></div><div className="rounded-2xl border border-zinc-800 bg-black/20 px-4 py-2 text-right"><p className="font-mono text-[7px] tracking-[.16em] text-zinc-700">CONVICTION</p><p className="mt-1 text-lg font-semibold text-cyan-300">{score}<span className="text-xs text-zinc-600">/100</span></p><p className="font-mono text-[7px] text-zinc-600">{label(s?.quality?.confidence||"LOW")}</p></div></div>
 <div className="mt-5 grid gap-2 sm:grid-cols-4"><Metric label="CURRENT" value={fmt(s?.price)}/><Metric label="ENTRY" value={hasAccess?fmt(s?.entry):"PROTECTED"}/><Metric label="STOP" value={hasAccess?fmt(s?.stop):"PROTECTED"}/><Metric label="R:R" value={hasAccess&&s?.riskReward?`${fmt(s.riskReward)}R`:"—"}/></div>
 <div className="mt-4 grid gap-2 sm:grid-cols-3">{[0,1,2].map(i=><Metric key={i} label={`TP${i+1}`} value={hasAccess&&targets[i]?.price?fmt(targets[i].price):"—"} sub={targets[i]?.liquidityClass?label(targets[i].liquidityClass):targets[i]?.timeframe?label(targets[i].timeframe):undefined}/>)}</div>
 <div className="mt-5 overflow-hidden rounded-2xl border border-zinc-900 bg-black/15"><div className="grid grid-cols-5 border-b border-zinc-900 px-3 py-2 font-mono text-[7px] tracking-[.14em] text-zinc-700">{rows.map(r=><span key={r.tf} className="text-center">{r.tf}</span>)}</div><div className="grid grid-cols-5 px-3 py-3">{rows.map(r=><div key={r.tf} className="text-center"><p className={`text-[9px] font-medium ${r.trend==="bullish"?"text-emerald-300":r.trend==="bearish"?"text-red-300":"text-zinc-500"}`}>{label(r.trend)}</p><p className="mt-1 font-mono text-[7px] text-zinc-700">{label(r.structure)}</p></div>)}</div></div>
 <div className="mt-5 grid gap-3 md:grid-cols-3"><Thesis title="STRUCTURE" text={th.structural||"Structure is being evaluated by the engine."}/><Thesis title="LIQUIDITY" text={th.liquidity||"Liquidity map is being evaluated."}/><Thesis title="ENTRY" text={th.entry||"Entry is waiting for confirmation."}/></div>
 <div className="mt-4 rounded-xl border border-zinc-900 bg-black/20 px-4 py-3"><div className="flex items-center gap-2"><Target className="h-3.5 w-3.5 text-cyan-400"/><span className="font-mono text-[8px] tracking-[.14em] text-zinc-600">INVALIDATION</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{th.invalidation||"No setup is active."}</p></div>
 <div className="mt-5 flex flex-col gap-3 border-t border-zinc-900 pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{(s?.reasons||[]).slice(0,3).map((r:string,i:number)=><span key={i} className="rounded-full border border-zinc-900 px-2.5 py-1 text-[8px] text-zinc-600">{r}</span>)}</div>{id&&<Link href={`/analysis?setup=${encodeURIComponent(id)}`} className="inline-flex items-center gap-1 font-mono text-[8px] text-cyan-400 transition hover:text-cyan-200">OPEN ANALYSIS <ArrowUpRight className="h-3 w-3"/></Link>}</div></div></article>}
function Badge({children,good}:{children:React.ReactNode;good?:boolean}){return <span className={`rounded-full border px-2 py-1 font-mono text-[7px] tracking-[.1em] ${good?"border-emerald-400/15 text-emerald-400":"border-zinc-800 text-zinc-600"}`}>{children}</span>}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-xl border border-zinc-900 bg-black/15 p-3"><p className="font-mono text-[7px] tracking-[.16em] text-zinc-700">{label}</p><p className="mt-1.5 text-xs font-medium text-zinc-300">{value}</p>{sub&&<p className="mt-1 font-mono text-[7px] text-zinc-700">{sub}</p>}</div>}
function Thesis({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-zinc-900 bg-black/10 p-3.5"><p className="font-mono text-[7px] tracking-[.16em] text-zinc-700">{title}</p><p className="mt-2 text-[10px] leading-5 text-zinc-500">{text}</p></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-zinc-800/80 bg-zinc-950/70 p-4"><div className="flex items-center justify-between"><span className="text-zinc-700">{icon}</span><span className="font-mono text-[7px] tracking-[.18em] text-zinc-700">{label}</span></div><p className="mt-3 text-lg font-semibold text-zinc-200">{value}</p></div>}
