"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowUpRight, BarChart3, ChevronRight, CircleDot, LockKeyhole, Radar, ShieldCheck, Loader2, SlidersHorizontal, Zap, Crosshair, Clock3 } from "lucide-react";
import StandaloneShell from "./standalone-shell";
import AccountProfilePage from "./profile-page";

const Empty=({title,body}:{title:string;body:string})=><div className="nart-card rounded-2xl border border-zinc-800/80 bg-zinc-950/75 px-5 py-14 text-center sm:px-6 sm:py-16"><CircleDot className="mx-auto h-6 w-6 text-zinc-700"/><h3 className="mt-4 text-sm font-medium text-zinc-300">{title}</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-zinc-600">{body}</p></div>;

export function HomePage(){return <StandaloneShell>
  <section className="relative overflow-hidden pb-7 pt-1 sm:pb-9">
    <div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/[.035] blur-3xl"/>
    <div className="relative max-w-3xl">
      <div className="flex items-center gap-2">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.75)]"/>
        <span className="font-mono text-[8px] font-medium tracking-[.24em] text-zinc-600">TRADING INTELLIGENCE</span>
      </div>
      <h1 className="mt-4 text-[2.35rem] font-semibold leading-[1.04] tracking-[-.045em] text-white sm:text-5xl">Trading Setups, Reimagined.</h1>
      <p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500 sm:text-[15px]">Real-time market intelligence that helps you find, understand, and execute high-quality trading setups.</p>
    </div>
    <div className="mt-7 flex items-center gap-3 border-t border-zinc-900/90 pt-4">
      <Link href="/setups" className="inline-flex items-center gap-2 rounded-lg bg-cyan-400 px-3.5 py-2.5 text-[9px] font-semibold tracking-wide text-black transition hover:bg-cyan-300">SCAN SETUPS <ArrowUpRight className="h-3.5 w-3.5"/></Link>
      <span className="font-mono text-[8px] tracking-[.16em] text-zinc-700">MARKET DESK / READY</span>
    </div>
  </section>

  <div className="grid overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950/55 md:grid-cols-3">
    <HomeCard href="/setups" icon={<Radar/>} label="SETUPS" title="Find the trade" text="Evaluated opportunities with direction, quality and risk defined." />
    <HomeCard href="/analysis" icon={<BarChart3/>} label="ANALYSIS" title="Read the market" text="Structure, momentum and confluence behind the setup." />
    <HomeCard href="/history" icon={<Clock3/>} label="HISTORY" title="Review the record" text="Previous setups and outcomes in one focused journal." />
  </div>

  <section className="mt-4 border-y border-zinc-900/90 py-3">
    <div className="grid sm:grid-cols-4">
      <DeskMetric label="SCANNER" value="Ready"/><DeskMetric label="ANALYSIS" value="Ready"/><DeskMetric label="HISTORY" value="Tracking"/><DeskMetric label="RISK" value="Defined"/>
    </div>
  </section>
</StandaloneShell>}

function HomeCard({href,icon,label,title,text}:{href:string;icon:ReactNode;label:string;title:string;text:string}){return <Link href={href} className="group border-b border-zinc-900/90 p-4 transition hover:bg-white/[.018] md:border-b-0 md:border-r last:border-r-0"><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-zinc-800 bg-black/30 text-cyan-400 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><ChevronRight className="h-4 w-4 text-zinc-700 transition group-hover:translate-x-0.5 group-hover:text-cyan-400"/></div><p className="mt-5 font-mono text-[7px] tracking-[.18em] text-zinc-600">{label}</p><p className="mt-1 text-sm font-medium text-zinc-200">{title}</p><p className="mt-1 text-xs leading-5 text-zinc-600">{text}</p></Link>}
function DeskMetric({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between px-1 py-2.5 sm:block sm:px-3"><span className="font-mono text-[7px] tracking-[.18em] text-zinc-700">{label}</span><span className="text-xs text-zinc-500 sm:mt-1 sm:block">{value}</span></div>}

function SetupGate(){const [now,setNow]=useState(Date.now());const [premium,setPremium]=useState(false);useEffect(()=>{const read=()=>setPremium(Number(localStorage.getItem("kitsetups_premium_until")||0)>Date.now());read();const id=setInterval(()=>{setNow(Date.now());read()},1000);return()=>clearInterval(id)},[]);const profile=typeof window!=="undefined"?localStorage.getItem("kitsetups_user_profile"):null;const created=profile?Number(new Date(JSON.parse(profile).createdAt).getTime()):now;const until=premium?Number(localStorage.getItem("kitsetups_premium_until")):created+3*24*60*60*1000;const ms=Math.max(0,until-now),days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000);if(ms>0)return <div className="mb-5 rounded-2xl border border-emerald-500/15 bg-gradient-to-r from-emerald-500/[.05] to-transparent p-4"><div className="flex items-center justify-between gap-3"><span className="font-mono text-[9px] tracking-[.18em] text-emerald-400">{premium?"PREMIUM ACCESS":"FREE ACCESS"}</span><span className="flex shrink-0 items-center gap-1.5 font-mono text-[9px] text-zinc-500"><Loader2 className="h-3 w-3 animate-spin text-emerald-400"/>{days}d {hours}h remaining</span></div><p className="mt-2 text-xs text-zinc-500">{premium?"Full setup visibility is active for your 30-day premium period.":"Your full setup access is active during the 3-day trial."}</p></div>;return <div className="relative overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950"><div className="pointer-events-none select-none p-5 blur-md opacity-35"><div className="grid gap-3 sm:grid-cols-2"><div className="h-32 rounded-xl border border-zinc-800 bg-zinc-900"/><div className="h-32 rounded-xl border border-zinc-800 bg-zinc-900"/></div></div><div className="absolute inset-0 flex items-center justify-center bg-black/65 p-5 text-center"><div><LockKeyhole className="mx-auto h-5 w-5 text-cyan-400"/><p className="mt-3 text-sm font-medium text-white">Premium setups locked</p><p className="mt-1 max-w-sm text-xs leading-5 text-zinc-500">Your access has expired. Subscribe for $30 USDT on BNB Smart Chain to unlock every setup for 30 days.</p><Link href="/profile" className="mt-4 inline-flex rounded-xl bg-cyan-400 px-4 py-2.5 text-xs font-semibold text-black">UNLOCK PREMIUM</Link></div></div></div>}
export function SetupsPage(){return <StandaloneShell title="SETUPS"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] tracking-[.22em] text-cyan-500">TRADE RADAR</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-zinc-100">Evaluated opportunities</h2><p className="mt-1 max-w-xl text-xs leading-5 text-zinc-600">Only setups that meet the engine's conditions belong in this feed.</p></div><div className="flex items-center gap-2"><span className="inline-flex items-center gap-2 rounded-xl border border-zinc-800 bg-zinc-950/70 px-3 py-2 font-mono text-[9px] text-zinc-500"><SlidersHorizontal className="h-3.5 w-3.5 text-zinc-600"/> FILTERS</span><span className="inline-flex items-center gap-2 rounded-xl border border-emerald-400/10 bg-emerald-400/[.03] px-3 py-2 font-mono text-[9px] text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,.7)]"/> SCANNER LIVE</span></div></div><SetupGate/><div className="nart-card mb-5 overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950/75"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-900/80 px-4 py-3.5"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-cyan-400/[.07] text-cyan-400"><Radar className="h-4 w-4"/></span><div><p className="font-mono text-[8px] tracking-[.2em] text-zinc-600">SIGNAL FEED</p><p className="mt-0.5 text-sm font-medium text-zinc-300">Awaiting evaluated market data</p></div></div><span className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-black/20 px-2.5 py-1.5 font-mono text-[8px] text-zinc-600"><Clock3 className="h-3 w-3"/> LIVE</span></div><div className="grid grid-cols-2 divide-x divide-zinc-900/80 sm:grid-cols-4"><FeedMetric icon={<Crosshair/>} label="QUALITY" value="—"/><FeedMetric icon={<Zap/>} label="MOMENTUM" value="—"/><FeedMetric icon={<BarChart3/>} label="TIMEFRAME" value="—"/><FeedMetric icon={<ShieldCheck/>} label="RISK" value="—"/></div></div><Empty title="No setups to display" body="No evaluated setup is available right now. The feed stays empty rather than presenting a trade without sufficient market confirmation."/></StandaloneShell>}
function FeedMetric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="flex items-center gap-2.5 px-3 py-3.5"><span className="text-zinc-700">{icon}</span><div><p className="font-mono text-[7px] tracking-widest text-zinc-700">{label}</p><p className="mt-0.5 text-xs font-medium text-zinc-500">{value}</p></div></div>}
export function AnalysisPage(){return <StandaloneShell title="MARKET ANALYSIS"><div className="grid gap-3 md:grid-cols-3"><Panel title="Market regime" value="—"/><Panel title="Trend" value="—"/><Panel title="Momentum" value="—"/></div><div className="mt-5"><Empty title="Analysis data unavailable" body="This page is intentionally disconnected from the backend. It is ready to receive market-analysis records when the data layer is reconnected."/></div></StandaloneShell>}
function Panel({title,value}:{title:string;value:string}){return <div className="nart-card rounded-2xl border border-zinc-800/80 bg-zinc-950/75 p-5 transition hover:border-cyan-400/15"><p className="font-mono text-[9px] tracking-widest text-zinc-600">{title}</p><p className="mt-4 text-xl font-semibold text-zinc-500">{value}</p></div>}
export function ProfilePage(){return <AccountProfilePage/>}
