import Link from "next/link";
import AppShell from "@/components/app-shell";

const setups = [
  { pair: "BTCUSDT", side: "LONG", grade: "A+", price: "76,920.40", entry: "76,845.20", stop: "76,420.00", target: "78,480.00", rr: "3.42R", confidence: "94%", status: "ACTIVE" },
  { pair: "ETHUSDT", side: "SHORT", grade: "A", price: "4,216.80", entry: "4,228.10", stop: "4,275.00", target: "4,082.00", rr: "3.12R", confidence: "89%", status: "ACTIVE" },
  { pair: "SOLUSDT", side: "LONG", grade: "A+", price: "196.42", entry: "194.80", stop: "190.20", target: "211.50", rr: "3.63R", confidence: "96%", status: "LOCKED" },
];

function Page({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <AppShell><main className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><div className="mb-8"><p className="font-mono text-[9px] font-black tracking-[0.28em] text-cyan-400/70">{eyebrow}</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">{description}</p></div>{children}</main></AppShell>;
}

function SetupCard({ setup }: { setup: typeof setups[number] }) {
  const long = setup.side === "LONG";
  return <article className="overflow-hidden rounded-[28px] border border-white/[0.07] bg-[#090a0b] transition hover:-translate-y-0.5 hover:border-cyan-400/20"><div className={`h-px ${long ? "bg-emerald-400/40" : "bg-red-400/40"}`} /><div className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-mono text-lg font-bold">{setup.pair}</h2><span className={`border px-2 py-1 font-mono text-[8px] font-bold tracking-[0.16em] ${long ? "border-emerald-400/20 text-emerald-400" : "border-red-400/20 text-red-400"}`}>{setup.side}</span></div><p className="mt-2 font-mono text-[7px] tracking-[0.16em] text-zinc-600">LIVE ENGINE · 15M / 1H</p></div><div className="text-right"><span className="font-mono text-[8px] font-bold tracking-[0.14em] text-cyan-300">{setup.status}</span><p className="mt-1 font-mono text-xs font-bold">{setup.grade}</p></div></div><div className="my-6 border-y border-white/[0.05] py-5"><p className="font-mono text-[7px] tracking-[0.2em] text-zinc-600">CURRENT MARKET PRICE</p><p className="mt-1 font-mono text-3xl font-bold">${setup.price}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["ENTRY",setup.entry,"text-cyan-300"],["STOP",setup.stop,"text-red-300"],["TARGET",setup.target,"text-emerald-300"],["RISK / REWARD",setup.rr,"text-white"]].map(([label,value,color])=><div key={label} className="rounded-2xl bg-white/[0.025] p-3"><p className="font-mono text-[7px] tracking-[0.16em] text-zinc-600">{label}</p><p className={`mt-2 font-mono text-sm font-bold ${color}`}>{setup.status === "LOCKED" && label !== "RISK / REWARD" ? "••••••" : value}</p></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-white/[0.05] pt-4"><span className="font-mono text-[8px] tracking-[0.14em] text-zinc-600">CONFIDENCE</span><span className="font-mono text-xs font-bold text-cyan-300">{setup.confidence}</span></div></div></article>;
}

export function HomePage() { return <Page eyebrow="KITSETUPS" title="Trading intelligence, simplified." description="A clean command center for market structure, trade setups and performance tracking."><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-[28px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.2em] text-zinc-600">MARKET STATE</p><p className="mt-3 text-2xl font-black text-emerald-400">LIVE</p><p className="mt-1 text-xs text-zinc-600">Scanner interface ready</p></div><div className="rounded-[28px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.2em] text-zinc-600">ACTIVE SETUPS</p><p className="mt-3 text-2xl font-black">03</p><p className="mt-1 text-xs text-zinc-600">Awaiting fresh engine data</p></div><div className="rounded-[28px] border border-cyan-400/10 bg-cyan-400/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.2em] text-cyan-400/70">ENGINE</p><p className="mt-3 text-2xl font-black text-cyan-300">READY</p><p className="mt-1 text-xs text-zinc-600">Frontend is backend-independent</p></div></div><div className="mt-8 flex items-end justify-between"><div><p className="font-mono text-[8px] tracking-[0.2em] text-zinc-600">OVERVIEW</p><h2 className="mt-2 text-xl font-black">Latest setups</h2></div><Link href="/setups" className="font-mono text-[8px] font-bold tracking-[0.16em] text-cyan-300">VIEW ALL →</Link></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{setups.slice(0,2).map(s=><SetupCard key={s.pair} setup={s}/>)}</div></Page>; }

export function SetupsPage() { return <Page eyebrow="SETUPS" title="Live trade setups" description="Structured opportunities will be supplied by the new trading backend. The page is now fully independent from it."><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{["ALL","LONG","SHORT","ACTIVE","WATCH"].map((x,i)=><span key={x} className={`whitespace-nowrap rounded-full border px-3 py-2 font-mono text-[8px] font-bold tracking-[0.14em] ${i===0?"border-cyan-400/20 bg-cyan-400/[0.05] text-cyan-300":"border-white/[0.07] text-zinc-600"}`}>{x}</span>)}</div><div className="grid gap-4 lg:grid-cols-2">{setups.map(s=><SetupCard key={s.pair} setup={s}/>)}</div></Page>; }

export function AnalysisPage() { return <Page eyebrow="ANALYSIS" title="Market analysis" description="Select a market to inspect structure, momentum and execution context. Live analysis will plug into this page through the fresh backend later."><div className="rounded-[28px] border border-white/[0.07] bg-[#090a0b] p-5"><div className="flex flex-col gap-3 sm:flex-row"><input aria-label="Market" defaultValue="BTCUSDT" className="h-12 flex-1 rounded-2xl border border-white/[0.07] bg-white/[0.025] px-4 font-mono text-xs text-white outline-none placeholder:text-zinc-700 focus:border-cyan-400/30" placeholder="Search market..." /><button className="h-12 rounded-2xl border border-cyan-400/20 bg-cyan-400/[0.06] px-6 font-mono text-[8px] font-black tracking-[0.16em] text-cyan-300">ANALYZE</button></div></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div className="rounded-[24px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">STRUCTURE</p><p className="mt-3 text-xl font-black text-emerald-400">BULLISH</p></div><div className="rounded-[24px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">MOMENTUM</p><p className="mt-3 text-xl font-black">EXPANDING</p></div><div className="rounded-[24px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">BIAS</p><p className="mt-3 text-xl font-black text-cyan-300">LONG</p></div></div></Page>; }

export function HistoryPage() { return <Page eyebrow="HISTORY" title="Signal track record" description="A clean record of published setups and how they performed over time."><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-[24px] border border-white/[0.07] bg-white/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">TOTAL SIGNALS</p><p className="mt-2 text-2xl font-black">—</p></div><div className="rounded-[24px] border border-emerald-400/10 bg-emerald-400/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">WINS</p><p className="mt-2 text-2xl font-black text-emerald-400">—</p></div><div className="rounded-[24px] border border-red-400/10 bg-red-400/[0.025] p-5"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">LOSSES</p><p className="mt-2 text-2xl font-black text-red-400">—</p></div></div><div className="mt-6 overflow-hidden rounded-[28px] border border-white/[0.07] bg-[#090a0b]"><div className="border-b border-white/[0.06] px-5 py-4"><p className="font-mono text-[8px] font-bold tracking-[0.2em] text-zinc-500">RECENT SIGNALS</p></div><div className="divide-y divide-white/[0.05]">{setups.map((s,i)=><div key={s.pair} className="grid gap-3 px-5 py-5 sm:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><p className="font-mono text-sm font-bold">{s.pair}</p><p className="mt-1 text-[10px] text-zinc-600">{i===0?"Today":"Awaiting backend history"}</p></div><div><p className="font-mono text-[7px] tracking-[0.14em] text-zinc-600">DIRECTION</p><p className={`mt-1 font-mono text-xs font-bold ${s.side==="LONG"?"text-emerald-400":"text-red-400"}`}>{s.side}</p></div><div><p className="font-mono text-[7px] tracking-[0.14em] text-zinc-600">STATUS</p><p className="mt-1 font-mono text-xs font-bold text-cyan-300">{s.status}</p></div><div><p className="font-mono text-[7px] tracking-[0.14em] text-zinc-600">OUTCOME</p><p className="mt-1 font-mono text-xs text-zinc-500">—</p></div></div>)}</div></div></Page>; }

export function ProfilePage() { return <Page eyebrow="PROFILE" title="Your profile" description="Account preferences and access details will live here independently of the trading engine API."><div className="rounded-[30px] border border-white/[0.07] bg-[#090a0b] p-6"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full border border-cyan-400/15 bg-cyan-400/[0.05] font-mono text-lg text-cyan-300">K</div><div><p className="font-mono text-sm font-bold">KitSetups Trader</p><p className="mt-1 text-xs text-zinc-600">Frontend profile · backend connection pending</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/[0.025] p-4"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">PLAN</p><p className="mt-2 font-mono text-sm font-bold text-cyan-300">FREE</p></div><div className="rounded-2xl bg-white/[0.025] p-4"><p className="font-mono text-[8px] tracking-[0.16em] text-zinc-600">STATUS</p><p className="mt-2 font-mono text-sm font-bold text-emerald-400">READY</p></div></div></div></Page>; }
